name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  DOCKER_HUB_USERNAME: dheerukanala
  IMAGE_NAME: streamlituiforai

jobs:
  publish_images:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: build image
      run: docker build -t dheerukanala/streamlituiforai:latest .

    - name: push to docker hub
      run: |
         docker login -u dheerukanala -p ${{ secrets.DOCKER_HUB_TOKEN }}
         docker push dheerukanala/streamlituiforai:latest
    
